### ISSUE TITLE
Release kernel sources..

### ISSUE THREAD

**Issue by naveensingh** [vivo/vivo.github.io#1]
Please release kernel sources for Vivo devices & a method to unlock bootloader.
Users privacy & security isn't at risk if you do this because no one really tinkers with these things other than developers & hobbyists.
Google & other OEM do it already, what's the problem?

**Comment by DavidWithTuxedo** [comment]
> Please release kernel sources for Vivo devices & a method to unlock bootloader.
> Users privacy & security isn't at risk if you do this because no one really tinkers with these things other than developers & hobbyists.
> Google & other OEM do it already, what's the problem?

Hello Bro! What model is your vivo phone?

It seems that they are beginning to release kernel sources of some models sold in Europe and the USA. You can see them at the [Vivo-OpenSource](https://opensource.vivo.com/Project) .

I don't think that they will release kernel sources of devices sold in other areas. GPL license lacks sufficient enforcement power for other areas.

**Comment by naveensingh** [comment]
I have an X21 and Y51L and yes, the source code isn't on the list.
What model is yours?

Thanks for the link, Bro :)

**Comment by mxpro2003** [comment]
> I have an X21 and Y51L and yes, the source code isn't on the list.
> What model is yours?
> 
> Thanks for the link, Bro :)

My devices:
`Y81(PD1732)`  `Y51L(PD1510)`

Sadly, kernel sources of them are all unavailable.

**Comment by DavidWithTuxedo** [comment]
> I have an X21 and Y51L and yes, the source code isn't on the list.
> What model is yours?
> 
> Thanks for the link, Bro :)

I have Y81, Y51L and X21 , their kernel sources are both nowhere to be found.

**Comment by DavidWithTuxedo** [comment]
> I have an X21 and Y51L and yes, the source code isn't on the list.
> What model is yours?
> 
> Thanks for the link, Bro :)

Here you can see their statement about Opensource.
https://github.com/vivo/dubbo-js/issues/2

**Comment by DavidWithTuxedo** [comment]
> > I have an X21 and Y51L and yes, the source code isn't on the list.
> > What model is yours?
> > Thanks for the link, Bro :)
> 
> Here you can see their statement about Opensource.
> https://github.com/vivo/dubbo-js/issues/2

Well, they have closed the issue section of that repo. Maybe the next one is here.

**Comment by node** [comment]
Hi  @Naveen3Singh  Thanks for your feedback.  As @DavidWithTuxedo  said you can visit and download source code  by https://opensource.vivo.com/Project , and we will release more projects by that website .

**Comment by node** [comment]
> > > I have an X21 and Y51L and yes, the source code isn't on the list.
> > > What model is yours?
> > > Thanks for the link, Bro :)
> > 
> > 
> > Here you can see their statement about Opensource.
> > https://github.com/vivo/dubbo-js/issues/2
> 
> Well, they have closed the issue section of that repo. Maybe the next one is here.

I found that "close" action . That is a fork project and your question is not related to that project .

**Comment by naveensingh** [comment]
Will do!
I hope vivo releases the source code for y51L and vivo X21. It seems both no longer get patches and security updates or any os updates.

Thanks @DavidWithTuxedo @node

**Comment by DavidWithTuxedo** [comment]
> > > > I have an X21 and Y51L and yes, the source code isn't on the list.
> > > > What model is yours?
> > > > Thanks for the link, Bro :)
> > > 
> > > 
> > > Here you can see their statement about Opensource.
> > > https://github.com/vivo/dubbo-js/issues/2
> > 
> > 
> > Well, they have closed the issue section of that repo. Maybe the next one is here.
> 
> I found that "close" action . That is a fork project and your question is not related to that project .

Thanks for your reply! First I apologize here for my unsuitable issue submitted early in that repo.

It seems that there is kernel source of VIVO Y3s which has similar CPU with VIVO Y81 on the "VIVO-OpenSource" website. Could you please release kernel source of VIVO Y81(PD1732)? This phone is announced in 2018.

Thanks in advance!

**Comment by DavidWithTuxedo** [comment]
@node 
As far as I know, even the "OPPO Mobile" has begun to release the kernel source code of their old models. Such as these on the picture
![082909050417_0IMG_20210829_090336](https://user-images.githubusercontent.com/85795570/131235038-b2c84eb7-38e3-4405-922f-40d4a8dba591.jpg)

**Dear VIVO, how about you?**
**So far,** have you released the kernel source code for **any models before 2020?**
![IMG_20210829_092523](https://user-images.githubusercontent.com/85795570/131235203-57be1245-41e9-45af-b5f4-5228d0995359.jpg)

**Comment by DavidWithTuxedo** [comment]
> > > > I have an X21 and Y51L and yes, the source code isn't on the list.
> > > > What model is yours?
> > > > Thanks for the link, Bro :)
> > > 
> > > 
> > > Here you can see their statement about Opensource.
> > > https://github.com/vivo/dubbo-js/issues/2
> > 
> > 
> > Well, they have closed the issue section of that repo. Maybe the next one is here.
> 
> I found that "close" action . That is a fork project and your question is not related to that project .

Indeed, that seems an "irrelevant question". But I have no choice. So could you please tell me where I can consult the VIVO for kernel OpenSource issues?

For OPPO users, they have [oppo-source](https://github.com/oppo-source) , oss@oppo.com and oppo_github@oppo.com to inqure about it.

For Samsung users, they have the [Samsung Opensource](https://opensource.samsung.com/) with perfect request mechanism.

For HUAWEI users, they have the [HUAWEI OpenSource](https://consumer.huawei.com/en/opensource/).

For XIAOMI users, they have the [XIAOMI OpenSource](https://github.com/micode).

For ZTE users, they have the [ZTE OpenSource](https://opensource.ztedevices.com/).

As one of VIVO users, we don't have any channels to consult kernel OpenSource issues, and only the kernel source code for models after 2020 is available on the [VIVO OpenSource](https://opensource.vivo.com/Project).

**Comment by node** [comment]
> > > > > I have an X21 and Y51L and yes, the source code isn't on the list.
> > > > > What model is yours?
> > > > > Thanks for the link, Bro :)
> > > > 
> > > > 
> > > > Here you can see their statement about Opensource.
> > > > https://github.com/vivo/dubbo-js/issues/2
> > > 
> > > 
> > > Well, they have closed the issue section of that repo. Maybe the next one is here.
> > 
> > 
> > I found that "close" action . That is a fork project and your question is not related to that project .
> 
> Indeed, that seems an "irrelevant question". But I have no choice. So could you please tell me where I can consult the VIVO for kernel OpenSource issues?
> 
> For OPPO users, they have [oppo-source](https://github.com/oppo-source) , [oss@oppo.com](mailto:oss@oppo.com) and [oppo_github@oppo.com](mailto:oppo_github@oppo.com) to inqure about it.
> 
> For Samsung users, they have the [Samsung Opensource](https://opensource.samsung.com/) with perfect request mechanism.
> 
> For HUAWEI users, they have the [HUAWEI OpenSource](https://consumer.huawei.com/en/opensource/).
> 
> For XIAOMI users, they have the [XIAOMI OpenSource](https://github.com/micode).
> 
> For ZTE users, they have the [ZTE OpenSource](https://opensource.ztedevices.com/).
> 
> As one of VIVO users, we don't have any channels to consult kernel OpenSource issues, and only the kernel source code for models after 2020 is available on the [VIVO OpenSource](https://opensource.vivo.com/Project).

Hi @DavidWithTuxedo You are right that here is "irrelevant question" again :)  And also I agree with you that developers can only visit and browse projects released by https://opensource.vivo.com/Project but have no channel to feedback or communicate other issues . 
Actually I am not responsible for mobile projects and know less about kernel things , but I think at least the kernel team should post a public email address by vivo open source website . I have pushed this . Wait feedback here .

**Comment by DavidWithTuxedo** [comment]
Long time no see!
Dear Mr. node, would you please tell me what is the result of the feedback?

**Comment by DavidWithTuxedo** [comment]
@node 
It seems that some new kernel source code has been released recently, but VIVO Y81 is still not included. 
![IMG_20211209_102832](https://user-images.githubusercontent.com/85795570/145328547-32ca33be-5517-4547-9777-ca95a037bcc6.jpg)
Please at least give me the contact information of the person in charge of the kernel open source, thank you very much!

**Comment by naveensingh** [comment]
>  I think at least the kernel team should post a public email address by vivo open source website . I have pushed this . Wait feedback here .

Anything on that?

If old devices are being discarded, might as well throw there kernel sources here (no need for any code change or extra work, just remove any proprietary stuff and push the damn thing) so people can do what they want with their devices instead of being locked up with an outdated software.

(...too much ;)?)

**Comment by DavidWithTuxedo** [comment]
Another 10 days have passed, don't respond?
@node 
At least let us know the result, right?

**Comment by node** [comment]
Guys I'm back here  with good news 👍 
1. Y81 kernel source has been released to https://opensource.vivo.com/Project    @DavidWithTuxedo  
2. Y51 and X21 are being processed internally and expected to be released to https://opensource.vivo.com/Project  soon .  @Naveen3Singh 

And also there is long term solution , you can feedback kernel open source issues by email mobileOSS@vivo.com, and this email is also posted on our open source website .

Really thanks that you guys' issues help us improve our open souce governance .

**Comment by naveensingh** [comment]
Hey @node 

Thank you very much for the update. This is very exciting news.

> Y51 and X21 are being processed internally and is expected to be released to https://opensource.vivo.com/Project soon

I'll keep watch

(@DavidWithTuxedo come see this mate)

**Comment by DavidWithTuxedo** [comment]
Thank you for your help! @node

I believe your positive and friendly attitude towards OpenSource will make you develop better.

**Comment by DavidWithTuxedo** [comment]
Seemly It's all just my wishful thinking, not real at all. There are some files missing for Y81's kernel source.
```bash
drivers/power/supply/vivo/battery.c
drivers/power/supply/vivo/power_control.c
drivers/power/supply/vivo/battery_interface.c
drivers/power/supply/vivo/bq25890h.c
drivers/power/supply/vivo/bq25601d.c
drivers/power/supply/vivo/Kconfig
... etc
```
I have written a email about this, just looking forward to the reply.

**Comment by node** [comment]
> > Hey @node
> > Thank you very much for the update. This is very exciting news.
> > > Y51 and X21 are being processed internally and is expected to be released to https://opensource.vivo.com/Project soon
> > 
> > 
> > I'll keep watch
> > (@DavidWithTuxedo come see this mate)
> 
> Hi Bro! It seems that the source of X21 is now available.
> 
> But there are some files missing for Y81's kernel source. So I'm not sure about whether the source of X21 is complete.
> 
> ```shell
> make k62v1_64_bsp_defconfig_PD1732
> drivers/power/Kconfig:7: can't open file "drivers/power/supply/vivo/Kconfig"
> ```
> 
> The "drivers/power/supply/vivo" folder is nowhere to find. I have written a email about this, just looking forward to the reply.

Hi @DavidWithTuxedo we can not support about Linux kernel issue under this project and this issue, you'd better feedback by the open souce website and the contact email, our Kernel team will process, hope your problem will be fixed . 

And also we will close this issue later. Thanks .

**Comment by aryanrai256** [comment]
> > Please release kernel sources for Vivo devices & a method to unlock bootloader.
> > Users privacy & security isn't at risk if you do this because no one really tinkers with these things other than developers & hobbyists.
> > Google & other OEM do it already, what's the problem?
> 
> Hello Bro! What model is your vivo phone?
> 
> It seems that they are beginning to release kernel sources of some models sold in Europe and the USA. You can see them at the [Vivo-OpenSource](https://opensource.vivo.com/Project) .
> 
> I don't think that they will release kernel sources of devices sold in other areas. GPL license lacks sufficient enforcement power for other areas.

I have vivo y15. I wanna unlock bootloader of this device. I tried so many commands but not working . So please help me.
![Uploading oem commands vivo.JPG…]()

**Comment by muhammadrafiasyddiq** [comment]
> > > Hai@node
> > > Terima kasih banyak atas pembaruannya. Ini adalah berita yang sangat menggembirakan.
> > > > Y51 dan X21 sedang diproses secara internal dan diharapkan akan segera dirilis ke https://opensource.vivo.com/Project
> > > 
> > > 
> > > Saya akan berjaga-jaga 
> > > (@DavidWithTuxedoayo lihat teman ini)
> > 
> > 
> > Hai Saudara! Tampaknya sumber X21 sekarang tersedia.
> > Tetapi ada beberapa file yang hilang untuk sumber kernel Y81. Jadi saya tidak yakin apakah sumber X21 sudah lengkap.
> > ```shell
> > make k62v1_64_bsp_defconfig_PD1732
> > drivers/power/Kconfig:7: can't open file "drivers/power/supply/vivo/Kconfig"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Folder "drivers/power/supply/vivo" tidak dapat ditemukan. Saya telah menulis email tentang ini, hanya menantikan balasannya.
> 
> Hai@DavidWithTuxedokami tidak dapat mendukung tentang masalah kernel Linux di bawah proyek ini dan masalah ini, Anda sebaiknya memberi umpan balik melalui situs web sumber terbuka dan email kontak, tim Kernel kami akan memproses, semoga masalah Anda akan diperbaiki.
> 
> Dan juga kami akan menutup masalah ini nanti. Terima kasih .

HEIII RELEASE SOURCE FULL WHY MANY MISSING 
DRIVERS/PEM
DRIVERS/POWER/SUPPLY/VIVO

**Comment by random-rando** [comment]
Vivo U20 sources please :(

**Comment by uis246** [comment]
Vivo 1726(Y85) doesn't seem to be listed on opensource.vivo.com

**Comment by shivam0724** [comment]
Vivo y91i (1816) is also not in the list of official kernel sources please add its kernel sources also

**Comment by misha99fr** [comment]
I have vivo y22, please add its sources, not Vivo y22s

**Comment by luxun4** [comment]
vivoY75(PD1718)Not here https://opensource.vivo.com/Project

**Comment by madaraUchiha78689** [comment]
Vivo y30 model (1938) is not available in Vivo open source

**Comment by NCLnclNCL** [comment]
> Seemly It's all just my wishful thinking, not real at all. There are some files missing for Y81's kernel source.
> 
> drivers/power/supply/vivo/battery.c
> drivers/power/supply/vivo/power_control.c
> drivers/power/supply/vivo/battery_interface.c
> drivers/power/supply/vivo/bq25890h.c
> drivers/power/supply/vivo/bq25601d.c
> drivers/power/supply/vivo/Kconfig
> ... etc
> I have written a email about this, just looking forward to the reply.

Coppy source from other source code

**Comment by icdada** [comment]
iqoo vivo Z5 model (PD2148) is not available in Vivo open source

**Comment by nrannn1-collab** [comment]
ช่วยฉันกลับไปเป็นค่ามาตรฐาน
